# If a option has many sub-options, and it's optional, then give it a `enable` sub-option. If not optional, don't use `enable`.

menu:
  - name: home
    link: /
    icon: <i class="fas fa-home"></i>
  - name: archives
    link: archives/
    icon: <i class="fas fa-archive"></i>
  - name: categories
    link: categories/
    icon: <i class="fas fa-th-list"></i>
  - name: tags
    link: tags/
    icon: <i class="fas fa-tags"></i>
  # - name: about
  #   link: about/
  #   icon: <i class="fas fa-user-edit"></i>

# Transform your image to those favicons in https://realfavicongenerator.net/.
favicon:
  appleTouchIcon: favicons/apple-touch-icon.png
  androidChromeLarge: favicons/android-chrome-192x192.png
  medium: favicons/favicon-32x32.png
  small: favicons/favicon-16x16.png
  safariPinnedTab: favicons/safari-pinned-tab.svg
  androidManifest: favicons/site.webmanifest
  msBrowserConfig: favicons/browserconfig.xml
  fallback: favicon.ico

# Must be an array.
keywords:
  - личный блог
  - LiteOtaku
  - посты

# https://creativecommons.org/licenses/
# by | by-sa | by-nd | by-nc | by-nc-sa | by-nc-nd
creativeCommons:

# Available: atom-one-dark | atom-one-light | solarized-dark | solarized-light
highlight: atom-one-dark

# Custom info in footer.
customInfo: Хостинг &mdash; <i class="fab fa-github-alt"></i><a href="https://pages.github.com/" target="_blank" rel="noreferrer noopener">GitHub Pages</a>

# Select all your webfont in a CDN like Google Fonts, and then copy `href` property in the `<link>` tag, like `link: //fonts.googleapis.com/css?family=Lato|Roboto+Condensed|Skranji|Ubuntu|Ubuntu+Mono`.
# Then set different fonts to different parts here.
customFont:
  enable: false
  link: //fonts.googleapis.com/css?family=Lato|Roboto+Condensed|Skranji|Ubuntu|Ubuntu+Mono
  all: Ubuntu
  title: Roboto Condensed
  subtitle: Roboto Condensed
  main: Ubuntu
  code: Ubuntu Mono

avatar: images/avatar.webp

logo: images/logo.webp

# Theme color.
# Need quote to prevent `#` from comment.
color: "#33363b"

googleVerification:

since: 2021

search: true

# `left`, `right`, `false`
sidebar: right

# Animation in Home, Archive, Category and Tag.
animate: false

busuanzi: true

# If you want ARIA generate excerpt, set it to the length you want. If you don't, leave it blank.
# Recomend to place `<!--more-->` to where you want to stop excerpt in content instead of use this option.
# Example: `autoExcerpt: 200`, use first 200 chars in post content as excerpt.
autoExcerpt: 150

# If you want to use MathJax, first fill a CDN link like `cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-MML-AM_CHTML`, then set `enable: true`.
# And set front-matter `mathjax: true` to the page you want to use it.
# You can also set `global: true` here to load MathJax in all pages.
# But it's not recommended because MathJax sources are too large, that's why ARIA doesn't contain them and ask for CDN.
mathjax:
  enable: false
  global:
  cdn:

# Note: `fontAwesome.loader` is `fontawesome.min.js`. `busuanzi` is `busuanzi.pure.mini.js`.
# If you don't know what you are doing, don't change it.
libCDN:
  enable: true
  fontAwesome:
    loader: //cdn.bootcdn.net/ajax/libs/font-awesome/5.14.0/js/fontawesome.min.js
    solid: //cdn.bootcdn.net/ajax/libs/font-awesome/5.14.0/js/solid.min.js
    brands: //cdn.bootcdn.net/ajax/libs/font-awesome/5.14.0/js/brands.min.js
    regular: //cdn.bootcdn.net/ajax/libs/font-awesome/5.14.0/js/regular.min.js
  busuanzi:
  normalize:
  highlight: //cdn.bootcdn.net/ajax/libs/highlight.js/10.1.2/highlight.min.js
  clipboard: //cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.6/clipboard.min.js
  # Don't use camelCase for hljs theme CSS files,
  # because they need to keep the same as highlight values.
  atom-one-dark:
  atom-one-light:
  solarized-dark:
  solarized-light:

social:
  enable: true
  links:
    - name: E-Mail
      link: mailto:liteotaku@gmail.com
      icon: <i class="fas fa-envelope"></i>
    - name: GitHub
      link: https://github.com/liteotaku
      icon: <i class="fab fa-github"></i>
    - name: Telegram
      link: https://t.me/liteotaku/
      icon: <i class="fab fa-telegram-plane"></i>

blogroll:
  enable: true
  links:
    - name: GitHub
      link: https://github.com/
      icon: <i class="fas fa-link"></i>
    - name: MDN
      link: https://developer.mozilla.org/
      icon: <i class="fas fa-link"></i>
    - name: Nunjucks
      link: https://mozilla.github.io/nunjucks/
      icon: <i class="fas fa-link"></i>

comment:
  enable: true
  issue:
    enable: true
    user:
    repo:
    perPage: 10
  disqusShortName:

reward:
  enable: false
  message: Поддержка автора!
  # weChatPayQRCode: images/WeChatPay.png
  # aliPayQRCode: images/AliPay.png
  # bitCoinQRCode: images/BitCoin.png
